### ISSUE TITLE
empty line without \r causes panic

### ISSUE THREAD

**Issue by vthriller** [whitfin/bytelines#1]
```rust
use std::io;
extern crate bytelines;
use bytelines::*;

fn main() {
    let stdin = io::stdin();
    for _ in stdin.lock().byte_lines() {}
}
```

```
$ echo | cargo run
thread 'main' panicked at 'attempt to subtract with overflow', …/bytelines-2.2.1/src/lib.rs:129:36
```

And the line that panics is:

```rust
// also "pop" a leading \r
if self.buffer[n - 1] == b'\r' {
```

**Comment by whitfin** [comment]
@vthriller nice catch! Will have a fix up for this in a few minutes.

**Comment by whitfin** [comment]
@vthriller I published v2.2.2 with a fix for this, can you please try it out and let me know?

**Comment by vthriller** [comment]
Works flawlessly now, at least for data that I'm currently fiddling with.

Thanks for such a quick response!

**Comment by whitfin** [comment]
@vthriller awesome, sorry for missing it initially! LMK if you need anything else!
