### ISSUE TITLE
Documentation contains incorrect types

### ISSUE THREAD

**Issue by dandavison** [whitfin/bytelines#2]
Apologies if I'm not understanding some Rust conventions but it seems to me that that the docs are misleading about the types yielded when iterating over lines. E.g.

```rust
// do something with the line, which is &[u8]
```

whereas really (AIUI) it's `Result<&[u8], Error>`. The same is true of several of the comments (and thus in the official docs on crates.io).

**Comment by whitfin** [comment]
It's technically correct, because it's referring the "line" of input - not the variable. But you're not wrong, it's misleading! Want to PR to fix it up? :)

**Comment by dandavison** [comment]
Thanks! Sure, I can do that. The thing that stopped me creating a PR was I wasn't sure whether I should write it out in full as `Result<&[u8], Error>` or whether there was a less verbose but still accurate way of saying that. But I guess you don't have a type alias, so I can't just write `Result<&[u8]>`, right?

And does one need to say what sort of Error/Result one is talking about...I'm still a bit new to Rust. I'll make the PR if you wouldn't mind answering those doubts.

**Comment by whitfin** [comment]
Sorry, missed this. Yes that seems fine :) 

You don't have to be perfect, as long as it's easy to understand. You could use `Result<&[u8], _>` too, so avoid having to define the error.

**Comment by dandavison** [comment]
Hi, no worries. PR coming.

Thanks for bytelines! I'm using it in [delta](https://github.com/dandavison/delta) where it is allowing me to address user requests to perform lossy decoding of utf-8 input and support non-utf-8 input.
